;=========================================
; Samsung
;=========================================

[Samsung]

flipboard.boxer.app=Briefing

com.opera.max.oem=Samsung Max

com.samsung.android.video=Samsung Video

com.samsung.android.themestore=Galaxy Themes

com.samsung.android.themecenter=Theme Center

com.samsung.android.app.notes=Samsung Notes

com.sec.android.service.health=Samsung Health

com.sec.android.app.voicenote=Voice Recorder

com.samsung.storyservice=Story Service

com.samsung.android.easysetup=Easy Setup

;=========================================
; Google
;=========================================

[Google]

com.google.android.music=Play Music

com.google.android.videos=Play Movies

com.google.android.apps.books=Books

com.google.android.apps.docs=Drive

com.google.android.talk=Hangouts

com.google.android.feedback=Feedback

;=========================================
; Microsoft
;=========================================

[Microsoft]

com.microsoft.office.word=Word

com.microsoft.office.excel=Excel

com.microsoft.office.powerpoint=PowerPoint

com.microsoft.skydrive=OneDrive

;=========================================
; Facebook
;=========================================

[Facebook]

com.facebook.katana=Facebook

com.facebook.system=Facebook System

com.facebook.services=Facebook Services

com.facebook.appmanager=Facebook Manager